export const QUOTES = [
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
  { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { quote: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller" },
  { quote: "Begin anywhere.", author: "John Cage" },
  { quote: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { quote: "It matters not how strait the gate, how charged with punishments the scroll, I am the master of my fate, I am the captain of my soul.", author: "William Ernest Henley" },
  { quote: "The power of imagining can make us infinite.", author: "John Muir" },
  { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { quote: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { quote: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { quote: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr." },
  { quote: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { quote: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { quote: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.", author: "Marilyn Monroe" },
  { quote: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein" },
  { quote: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
  { quote: "Life is what happens to us while we are making other plans.", author: "Allen Saunders" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
  { quote: "A woman is like a tea bag; you never know how strong it is until it's in hot water.", author: "Eleanor Roosevelt" },
  { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
  { quote: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { quote: "You can't blame gravity for falling in love.", author: "Albert Einstein" },
  { quote: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
  { quote: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", author: "J.K. Rowling" },
  { quote: "If you don't stand for something you will fall for anything.", author: "Gordon A. Eadie" },
  { quote: "You become what you believe.", author: "Oprah Winfrey" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "I can be changed by what happens to me. But I refuse to be reduced by it.", author: "Maya Angelou" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { quote: "You are enough just as you are.", author: "Meghan Markle" },
  { quote: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "An unexamined life is not worth living.", author: "Socrates" },
  { quote: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
  { quote: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso" },
  { quote: "You can never be overdressed or overeducated.", author: "Oscar Wilde" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "Do what you feel in your heart to be right – for you'll be criticized anyway.", author: "Eleanor Roosevelt" },
  { quote: "Peace begins with a smile.", author: "Mother Teresa" },
  { quote: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { quote: "Get busy living or get busy dying.", author: "Stephen King" },
  { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { quote: "It is better to be hated for what you are than to be loved for what you are not.", author: "André Gide" },
  { quote: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { quote: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "Defeat is not the worst of failures. Not to have tried is the true failure.", author: "George Edward Woodberry" },
  { quote: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
  { quote: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { quote: "Press forward. Do not stop, do not linger in your journey, but strive for the mark set before you.", author: "George Whitefield" },
  { quote: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { quote: "Light tomorrow with today.", author: "Elizabeth Barrett Browning" },
  { quote: "You do not find the happy life. You make it.", author: "Camilla Eyring Kimball" },
  { quote: "Joy is not in things; it is in us.", author: "Richard Wagner" },
  { quote: "Make each day your masterpiece.", author: "John Wooden" },
  { quote: "Wherever you go, go with all your heart.", author: "Confucius" },
  { quote: "Dreaming, after all, is a form of planning.", author: "Gloria Steinem" },
  { quote: "Change the game, don't let the game change you.", author: "Macklemore" },
  { quote: "Holding on to anger is like drinking poison and expecting the other person to die.", author: "Buddha" },
  { quote: "Wisdom begins in wonder.", author: "Socrates" },
  { quote: "Kindness is a mark of faith, and whoever has not kindness has not faith.", author: "Prophet Muhammad" },
  { quote: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau" },
  { quote: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { quote: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { quote: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { quote: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "So many books, so little time.", author: "Frank Zappa" },
  { quote: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
  { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { quote: "If you tell the truth, you don't have to remember anything.", author: "Mark Twain" },
  { quote: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard" },
  { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { quote: "Always forgive your enemies; nothing annoys them so much.", author: "Oscar Wilde" },
  { quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { quote: "We accept the love we think we deserve.", author: "Stephen Chbosky" },
  { quote: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { quote: "It is better to be hated for what you are than to be loved for what you are not.", author: "André Gide" },
  { quote: "Life is what happens to us while we are making other plans.", author: "Allen Saunders" },
  { quote: "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.", author: "Bill Keane" },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
  { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
  { quote: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { quote: "You can't blame gravity for falling in love.", author: "Albert Einstein" },
  { quote: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
  { quote: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.", author: "J.K. Rowling" },
  { quote: "You become what you believe.", author: "Oprah Winfrey" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "I can be changed by what happens to me. But I refuse to be reduced by it.", author: "Maya Angelou" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { quote: "You are enough just as you are.", author: "Meghan Markle" },
  { quote: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "An unexamined life is not worth living.", author: "Socrates" },
  { quote: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
  { quote: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso" },
  { quote: "You can never be overdressed or overeducated.", author: "Oscar Wilde" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { quote: "Peace begins with a smile.", author: "Mother Teresa" },
  { quote: "Courage is grace under pressure.", author: "Ernest Hemingway" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { quote: "Get busy living or get busy dying.", author: "Stephen King" },
  { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" }
];